"""rename_model_config_to_llm_settings

Revision ID: d5ed0f17ad3d
Revises: 0001
Create Date: 2026-05-02 16:48:22.234459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5ed0f17ad3d'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supervisors', 'model_config', new_column_name='llm_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supervisors', 'llm_settings', new_column_name='model_config')
    # ### end Alembic commands ###
